services:
  flashcards-web:
    image: ghcr.io/denysbielov/flashcards:latest
    ports:
      - "3000:3000"
    volumes:
      - flashcards-data:/app/data
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60
    restart: unless-stopped

volumes:
  flashcards-data:
